// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwYAM2Mai3kapSDCrIObEJjwvK5xJ2SMY',
    appId: '1:71617127087:web:f996a540618638bc6aaa5a',
    messagingSenderId: '71617127087',
    projectId: 'odit-crm',
    authDomain: 'odit-crm.firebaseapp.com',
    storageBucket: 'odit-crm.firebasestorage.app',
    measurementId: 'G-0F5ZYQDLBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3-fj4CpIBi8szwybjdKTmAqkYVm8kMTE',
    appId: '1:71617127087:android:dca71685e9b8ec2a6aaa5a',
    messagingSenderId: '71617127087',
    projectId: 'odit-crm',
    storageBucket: 'odit-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMcskuxXgej3nyS6KpBIhv7--rYAZwU9k',
    appId: '1:71617127087:ios:8ee8872df2b68c526aaa5a',
    messagingSenderId: '71617127087',
    projectId: 'odit-crm',
    storageBucket: 'odit-crm.firebasestorage.app',
    iosBundleId: 'com.example.oditCrmMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMcskuxXgej3nyS6KpBIhv7--rYAZwU9k',
    appId: '1:71617127087:ios:8ee8872df2b68c526aaa5a',
    messagingSenderId: '71617127087',
    projectId: 'odit-crm',
    storageBucket: 'odit-crm.firebasestorage.app',
    iosBundleId: 'com.example.oditCrmMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwYAM2Mai3kapSDCrIObEJjwvK5xJ2SMY',
    appId: '1:71617127087:web:2daf6557ad3d83646aaa5a',
    messagingSenderId: '71617127087',
    projectId: 'odit-crm',
    authDomain: 'odit-crm.firebaseapp.com',
    storageBucket: 'odit-crm.firebasestorage.app',
    measurementId: 'G-J4RDSRTFF4',
  );
}
